name: (s)ocial imagery
favicon: null
layout_spectrum: 1
typography_spectrum: 0.40163591247983277
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#020e0c'
    - '#572212'
    - '#c7a543'
    - '#9e7227'
  brandStrength: 0.5625
  lightness: 0.6484621348790824
  saturation: 0.7494150681886822
  rhythmicContrast: 0.9488728262949735
purpose: []
