name: (s)ocial imagery
favicon: null
layout_spectrum: 1
typography_spectrum: 0.76345
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0c0c'
    - '#353332'
    - '#ffffff'
    - '#615e5c'
    - '#969596'
  brandStrength: 0.5625
  lightness: 0.6484621348790824
  saturation: 0.7494150681886822
  rhythmicContrast: 0.9488728262949735
purpose: []
